CREATE DATABASE reservations;
GRANT ALL PRIVILEGES ON DATABASE reservations TO postgres;

CREATE DATABASE libraries;
GRANT ALL PRIVILEGES ON DATABASE libraries TO postgres;

CREATE DATABASE ratings;
GRANT ALL PRIVILEGES ON DATABASE ratings TO postgres;

CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON DATABASE auth TO postgres;

CREATE DATABASE statistics;
GRANT ALL PRIVILEGES ON DATABASE statistics TO postgres;
